/* Tree RedPos for  generated by http://behaviortrees.ftcteams.com */
package org.firstinspires.ftc.teamcode.BehaviorTrees.trees;

import com.ftcteams.behaviortrees.Node;
import com.ftcteams.behaviortrees.Sequence;
import com.ftcteams.behaviortrees.Failover;
import com.ftcteams.behaviortrees.Parallel;
import org.firstinspires.ftc.teamcode.BehaviorTrees.Actions.trajectories.RedPos.MoveBack;
import org.firstinspires.ftc.teamcode.BehaviorTrees.Actions.ReadObelisk;
import org.firstinspires.ftc.teamcode.BehaviorTrees.Actions.MoveToFire;
import org.firstinspires.ftc.teamcode.BehaviorTrees.Actions.MoveToPickup;
import org.firstinspires.ftc.teamcode.BehaviorTrees.Actions.RevUpIntake;
import org.firstinspires.ftc.teamcode.BehaviorTrees.Actions.firePatterns.FirePattern1;
import org.firstinspires.ftc.teamcode.BehaviorTrees.Actions.firePatterns.FirePattern2;
import org.firstinspires.ftc.teamcode.BehaviorTrees.Actions.firePatterns.FirePattern3;
import org.firstinspires.ftc.teamcode.BehaviorTrees.Actions.moveToIntake1;
import org.firstinspires.ftc.teamcode.BehaviorTrees.Actions.CheckAndIndex;
import org.firstinspires.ftc.teamcode.BehaviorTrees.Actions.DisengageIntake;
import org.firstinspires.ftc.teamcode.BehaviorTrees.Actions.MoveFrom1ToFire;
import org.firstinspires.ftc.teamcode.BehaviorTrees.Conditions.Obelisk1;
import org.firstinspires.ftc.teamcode.BehaviorTrees.Conditions.Obelisk2;


public class RedPos {
    public static Node root(){
        return new Sequence(
                new MoveBack(),
                new ReadObelisk(),
                new MoveToFire(),
                new Failover(
                        new Sequence(
                                new Obelisk1(),
                                new FirePattern1()),
                        new Sequence(
                                new Obelisk2(),
                                new FirePattern2()),
                        new FirePattern3()),
                new MoveToPickup(),
                new RevUpIntake(),
                new Parallel(2,
                        new moveToIntake1(),
                        new CheckAndIndex()),
                new DisengageIntake(),
                new MoveFrom1ToFire(),
                new Failover(
                        new Sequence(
                                new Obelisk1(),
                                new FirePattern1()),
                        new Sequence(
                                new Obelisk2(),
                                new FirePattern2()),
                        new FirePattern3()));
    }
}

/* TREE
->
|  [MoveBack]
|  [ReadObelisk]
|  [MoveToFire]
|  ?
|  |  ->
|  |  |  (Obelisk1)
|  |  |  [FirePattern1]
|  |  ->
|  |  |  (Obelisk2)
|  |  |  [FirePattern2]
|  |  [FirePattern3]
|  [MoveToPickup]
|  [RevUpIntake]
|  =2
|  |  [moveToIntake1]
|  |  [CheckAndIndex]
|  [DisengageIntake]
|  [MoveFrom1ToFire]
|  ?
|  |  ->
|  |  |  (Obelisk1)
|  |  |  [FirePattern1]
|  |  ->
|  |  |  (Obelisk2)
|  |  |  [FirePattern2]
|  |  [FirePattern3]
 */